### ISSUE TITLE
Tests failing after upgrade to Erlang 19

### ISSUE THREAD

**Issue by riverrun** [elixir-lang/elixir_make#13]
On my machine, the following tests fail after upgrading to Erlang 19:

- test specifying a makefile (Mix.Tasks.Compile.ElixirMakeTest)
- test specifying targets to run when cleaning (Mix.Tasks.Compile.ElixirMakeTest)
- test specifying targets (Mix.Tasks.Compile.ElixirMakeTest)
- test specifying env (Mix.Tasks.Compile.ElixirMakeTest)
- test specifying a cwd (Mix.Tasks.Compile.ElixirMakeTest)
- test running with a makefile (Mix.Tasks.Compile.ElixirMakeTest)
- test --verbose (Mix.Tasks.Compile.ElixirMakeTest)

After downgrading to Erlang 18.3, all the tests passed.

I'm using Erlang 19, Elixir 1.4-dev, and I'm on Arch Linux

Edit:
For each error, the os specific build error is printed, and this is the stacktrace:

   stacktrace:
       (mix) lib/mix.ex:274: Mix.raise/1
       (elixir_make) lib/mix/tasks/compile.make.ex:91: Mix.Tasks.Compile.ElixirMake.run/1
       (ex_unit) lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
       (ex_unit) lib/ex_unit/capture_io.ex:119: ExUnit.CaptureIO.do_capture_io/3
       test/mix/tasks/compile.make_test.exs:51: anonymous fn/0 in Mix.Tasks.Compile.ElixirMakeTest.test running with a makefile/1
       (elixir) lib/file.ex:1145: File.cd!/2
       test/mix/tasks/compile.make_test.exs:45: (test)

**Comment by riverrun** [comment]
PR #14 has fixed this. All the tests pass now.
